import { HashSet } from "./hashmap.js";

export default function testHashSet() {
  const hashSet = new HashSet();
  // This list of strings was generated by ChatGPT 4o mini with the
  // prompt "Generate a list of strings to store in a hash set for
  // testing"
  hashSet.set("apple");
  hashSet.set("banana");
  hashSet.set("cherry");
  hashSet.set("date");
  hashSet.set("elderberry");
  hashSet.set("fig");
  hashSet.set("grape");
  hashSet.set("honeydew");
  hashSet.set("kiwi");
  hashSet.set("lemon");
  hashSet.set("mango");
  hashSet.set("nectarine");

  console.log(
    "Add as many keys as possible without going over the load factor:",
  );
  console.log(hashSet.keys());
}
